#pragma once
/*
* Defines.hpp
* 
* Inclusions & definitions for the entire program.
*/

// =========================================================================== Std includes
#include <iostream>
#include <random>
#include <algorithm>
#include <type_traits>
#include <memory>
#include <cassert>
#include <cmath>
#include <string>
#include <vector>
#include <array>

// =========================================================================== Random functions
class Random {
public:
	Random() = delete;
	~Random() = delete;

	/// <summary>
	/// Get a random value in the range [0, 1) with a normal distribution.
	/// </summary>
	/// <returns></returns>
	static double normalRand();

	/// <summary>
	/// Get a random value in the range [0, 1) with a uniform distribution.
	/// </summary>
	/// <returns></returns>
	static double uniformRand();

private:
	static std::random_device device;
	static std::mt19937 method;
	static std::normal_distribution<double> normalDist;
	static std::uniform_real_distribution<double> uniformDist;
};

/// <summary>
/// Randomly determine the length of the next word.
/// </summary>
/// <returns></returns>
unsigned int getWordLength();

// =========================================================================== Helper functions

/// <summary>
/// Calculate the log[base b] of x.
/// </summary>
/// <param name="b">Base</param>
/// <param name="x">Value</param>
/// <returns></returns>
long double logn(long double b, long double x);

/// <summary>
/// Linear interpolation between a and b.
/// </summary>
/// <returns></returns>
double lerp(double a, double b, double t);

#define assertm(exp, msg) assert((void(msg), exp))


// ===========================================================================  Weight modifier functions

class WeightModifier;
extern std::vector<std::pair<std::shared_ptr<WeightModifier>, double>> weightModifiers;

/// <summary>
/// Register a new weight modifier class to use when determining the next letter.
/// </summary>
/// /// <param name="scalar">Scalar for weights generated by this class</param>
/// <typeparam name="T">Classname (Derived from WeightModifier)</typeparam>
template<class T>
void registerWeightModifier(double scalar) {
	static_assert(std::is_base_of<WeightModifier, T>::value, "T must derive from class WeightModifier");
	weightModifiers.emplace_back(std::make_pair(std::make_shared<T>(), scalar));
}